# Generated by Django 5.0.6 on 2025-02-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='comments',
            field=models.CharField(default='No comments', max_length=500),
            preserve_default=False,
        ),
    ]
