# Generated by Django 5.0.6 on 2025-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0002_phonenumber_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
